/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package splashscreen;

/**
 *
 * @author Vincent-Oracle
 */
import javax.swing.*;
import java.sql.*;
public class Login extends javax.swing.JFrame {

    /**
     * Creates new Login Form for users. The form appears as User interface that allows users to easily login 
     */
    
 
    public  Login() {
        initComponents();
    }
   
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPasword = new javax.swing.JPasswordField();
        button3 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        label3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Progress2 = new javax.swing.JProgressBar();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 255));
        setForeground(new java.awt.Color(255, 0, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        jTextField1.setBackground(java.awt.Color.green);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 20, 870, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\n\\Documents\\icons8-manager-64.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 70, 60));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setText("Username");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 70, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\n\\Documents\\padloc.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 60, 50));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 60, -1));

        txtUsername.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.blue, null, null));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 170, 40));

        txtPasword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.blue, null, null));
        getContentPane().add(txtPasword, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 200, 40));

        button3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button3.setText("LOGIN");
        button3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button3MouseClicked(evt);
            }
        });
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        getContentPane().add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 120, -1));

        button7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button7.setText("RESET");
        button7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button7MouseClicked(evt);
            }
        });
        getContentPane().add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 140, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Forgot password?");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 100, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        jLabel8.setForeground(java.awt.Color.red);
        jLabel8.setText("SignUp");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 60, -1));

        jSplitPane1.setRightComponent(label3);

        getContentPane().add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 20, 280));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\n\\Documents\\smallhouse.png")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 200, 160));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\n\\Documents\\passWord.png")); // NOI18N
        jLabel10.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel10PropertyChange(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("QUALITY HOMES");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(89, 89, 89)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 160, 80));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel11.setForeground(java.awt.Color.red);
        jLabel11.setText("Loading complete!!!");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 180, 30));

        Progress2.setBackground(java.awt.Color.black);
        getContentPane().add(Progress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 850, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\n\\Documents\\backgrounds.png")); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 4, 4, java.awt.Color.yellow));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 860, 160));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel13.setForeground(java.awt.Color.blue);
        jLabel13.setText("DOUBLE A RENTING FIRM");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 310, 30));

        jLabel14.setText("Click ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 242, 870, 10));

        jLabel15.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel15.setForeground(java.awt.Color.red);
        jLabel15.setText("SIGN IN");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel16.setText("or");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, -1, -1));
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, 40, -1));

        cancel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        cancel.setForeground(java.awt.Color.red);
        cancel.setText("*");
        cancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.blue, null, null));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 280, 30, 40));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\n\\Documents\\facebook.png")); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 90, 70));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\n\\Documents\\instagram-new--v2.png")); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 100, 70));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\n\\Documents\\twitter.png")); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 100, 70));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Contact us @www.doublearentingfirm.com");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, 20));

        jTextArea1.setBackground(java.awt.Color.pink);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 400, 170));

        jLabel22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 450, 280));

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\n\\Documents\\MAEIL.png")); // NOI18N
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 220, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel10PropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel10PropertyChange

    private void button3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button3MouseClicked
        // TODO add your handling code here
        panel1.setVisible(false);
       Estates est= new Estates();
       est.setVisible(true);
       button7.setEnabled(false);
  
        this.dispose();
        ImageIcon icon= new ImageIcon("1.jpg");
      JOptionPane.showInputDialog(null,"are ypu happy");
     
       JOptionPane.showMessageDialog(null,"Login Successfull!!!");
       JOptionPane.showMessageDialog(null,"PLEASE SELECT POSITION","Select Manager,Landlord,Agent,Receptionist",JOptionPane.WARNING_MESSAGE);
        
    //  log();
    }//GEN-LAST:event_button3MouseClicked

        
    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        String username= txtUsername.getText().toString();
        String password = txtPasword.getText();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/doubleadbs","root","vincent");
            Statement stmt=conn.createStatement();
            String select= "Select*from login;";
            ResultSet rs=stmt.executeQuery(select);
            while(rs.next()){
                String usersname=rs.getString("Username");
                String pass=rs.getString("Password");
                if((txtUsername!=null)&&(txtPasword!=null))
                        {
                     if(username.equals(usersname)&&password.equals(pass)){
                     new Estates().setVisible(true);
                    this.dispose();
                    JOptionPane.showMessageDialog(null,"Login Successful");
                    JOptionPane.showMessageDialog(null, "SELECT YOUR POSITION","Select to your position proceed",JOptionPane.WARNING_MESSAGE);
                    
                    
                    
                    //added messges
                    
                         this.dispose();
        ImageIcon icons= new ImageIcon("1.jpg");
      JOptionPane.showInputDialog(null,"are ypu happy");
    //  JOptionPane.showOptionDialog(null,"hellooo", "success", 55, 55, icons,null, EXIT_ON_CLOSE);
    //  JOptionPane.showInternalMessageDialog(null, "vinceny","hello", 50, icons);
       JOptionPane.showMessageDialog(null,"Login Successfull!!!");
       JOptionPane.showMessageDialog(null,"PLEASE SELECT POSITION","Select Manager,Landlord,Agent,Receptionist",JOptionPane.WARNING_MESSAGE);
        
                    
                    
                   }
                 else{
                    JOptionPane.showMessageDialog(null,"Wrong Username/Password","Login error,Please Fill credentials Correctly",JOptionPane.ERROR_MESSAGE);
                }
                }
                else if (txtUsername==null||txtPasword==null){
                    JOptionPane.showMessageDialog(null,"Please enter your credentials ","",JOptionPane.ERROR_MESSAGE);
                     }
             }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
             JOptionPane.showMessageDialog(null,"Please enter your credentials ","",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void button7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button7MouseClicked
        // TODO add your handling code here:
       Reset rest= new Reset();
       this.dispose();
       rest.setVisible(true);
       button3.setEnabled(true);
    }//GEN-LAST:event_button7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        Reset rest= new Reset();
       this.dispose();
       rest.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        // TODO add your handling code here:
        if(evt.getSource()==cancel){
            txtUsername.setText(" ");
        }
    }//GEN-LAST:event_cancelMouseClicked

    /**
     * @param args the command line arguments
     */
   
    /**
     *
     * @param args
     */
    
        
        
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
   
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar Progress2;
    public javax.swing.JButton button3;
    private javax.swing.JButton button7;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JLabel label3;
    public javax.swing.JPanel panel1;
    private javax.swing.JPasswordField txtPasword;
    public static javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
